# Nym Mainnet Node Configuration
# This is the official configuration template for Nym mainnet nodes

[network]
listen_addr = "0.0.0.0:30333"
bootstrap_peers = [
    "bootstrap1.nym.network:30333",
    "bootstrap2.nym.network:30333", 
    "bootstrap3.nym.network:30333",
    "bootstrap4.nym.network:30333",
    "bootstrap5.nym.network:30333"
]
max_peers = 100
enable_privacy_routing = true
mix_strategy = "random_delay"
cover_traffic_rate = 0.1

[storage]
data_dir = "~/.nym-node/data"
max_storage_gb = 500
enable_pruning = true
pruning_interval_hours = 24
enable_archival = true

[consensus]
consensus_type = "Hybrid"
pow_enabled = true
pos_enabled = true
pow_weight = 0.5
pos_weight = 0.5
block_time_seconds = 60
finality_threshold = 67

[rpc]
enabled = true
listen_addr = "127.0.0.1:9933"
max_connections = 1000
auth_enabled = true

[compute]
enabled = true
max_jobs = 50
supported_runtimes = ["wasm", "docker", "tee", "gpu"]

[compute.resource_limits]
max_memory_mb = 8192
max_cpu_cores = 4
max_execution_time_seconds = 3600

[economics]
enable_adaptive_emissions = true
enable_fee_burning = true
min_stake_amount = 10000
validator_reward_percentage = 0.03

[logging]
level = "warn"
format = "json"
file_path = "~/.nym-node/logs/node.log"