# Nym Node Configuration - Node 1
node_id = "node1"

[network]
chain_id = "nym-testnet-local"
listen_addr = "0.0.0.0:30334"
max_peers = 50
enable_privacy_routing = true
mix_strategy = "random_delay"
cover_traffic_rate = 0.1

[storage]
data_dir = "testnet/node1/data"
max_storage_gb = 10
enable_pruning = true
pruning_interval_hours = 24
enable_archival = false

[consensus] 
consensus_type = "Hybrid"
pow_enabled = true
pos_enabled = true
pow_weight = 0.5
pos_weight = 0.5
block_time_seconds = 5
finality_threshold = 67

[rpc]
enabled = true
listen_addr = "127.0.0.1:9934"
max_connections = 100
auth_enabled = false

[privacy]
stealth_addresses_enabled = true
confidential_transactions_enabled = true
transaction_mixing_enabled = true
anonymity_set_size = 128
mixing_rounds = 3
multisig_stealth_enabled = true
sub_address_generation_enabled = true

[defi]
amm_enabled = true
lending_enabled = true
cross_chain_enabled = true
default_fee_rate = 30
mev_protection_enabled = true
batch_size = 50
batch_interval = 2

[compute]
enabled = true
max_jobs = 5
supported_runtimes = ["wasm", "docker", "native"]

[economics]
enable_adaptive_emissions = true
enable_fee_burning = true
min_stake_amount = 1000
validator_reward_percentage = 0.05

[security]
signature_algorithm = "ML-DSA-44"
hash_algorithm = "SHAKE256"
quantum_resistance = true
audit_enabled = true

[logging]
level = "info"
format = "json"
